modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cluttered"
version = "${version}"
displayName = "Cluttered"
authors = "Blake, YellowChuJelly"
description = '''
Cluttered adds various furniture and blocks from different games.
'''
logoFile = "assets/cluttered/textures/block/willow_bookshelf_black_cat.png"

[[dependencies.cluttered]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cluttered]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cluttered]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
